./yolo Libtorch Detect YOLOv3 CPU FP32 ../../weights/yolov3u_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv3 GPU FP32 ../../weights/yolov3u_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv3 GPU FP16 ../../weights/yolov3u_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Detect YOLOv3 CPU FP32 ../../weights/yolov3u_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv3 GPU FP32 ../../weights/yolov3u_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv3 CPU FP16 ../../weights/yolov3u_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv3 GPU FP16 ../../weights/yolov3u_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv3 CPU INT8 ../../weights/yolov3u_int8.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv3 GPU INT8 ../../weights/yolov3u_int8.onnx bus.jpg
./yolo OpenCV Detect YOLOv3 CPU FP32 ../../weights/yolov3u_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv3 GPU FP32 ../../weights/yolov3u_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv3 CPU FP16 ../../weights/yolov3u_fp16.onnx bus.jpg
./yolo OpenCV Detect YOLOv3 GPU FP16 ../../weights/yolov3u_fp16.onnx bus.jpg
./yolo OpenVINO Detect YOLOv3 CPU FP32 ../../weights/yolov3u_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv3 GPU FP32 ../../weights/yolov3u_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv3 CPU FP16 ../../weights/yolov3u_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv3 GPU FP16 ../../weights/yolov3u_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv3 CPU INT8 ../../weights/yolov3u_int8.xml bus.jpg
./yolo OpenVINO Detect YOLOv3 GPU INT8 ../../weights/yolov3u_int8.xml bus.jpg
./yolo TensorRT Detect YOLOv3 GPU FP32 ../../weights/yolov3u_fp32.engine bus.jpg
./yolo TensorRT Detect YOLOv3 GPU FP16 ../../weights/yolov3u_fp16.engine bus.jpg
./yolo TensorRT Detect YOLOv3 GPU INT8 ../../weights/yolov3u_int8.engine bus.jpg


./yolo ONNXRuntime Detect YOLOv4 CPU FP32 ../../weights/yolov4_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv4 GPU FP32 ../../weights/yolov4_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv4 CPU FP16 ../../weights/yolov4_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv4 GPU FP16 ../../weights/yolov4_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv4 CPU INT8 ../../weights/yolov4_int8.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv4 GPU INT8 ../../weights/yolov4_int8.onnx bus.jpg
./yolo OpenCV Detect YOLOv4 CPU FP32 ../../weights/yolov4_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv4 GPU FP32 ../../weights/yolov4_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv4 CPU FP16 ../../weights/yolov4_fp16.onnx bus.jpg
./yolo OpenCV Detect YOLOv4 GPU FP16 ../../weights/yolov4_fp16.onnx bus.jpg
./yolo OpenVINO Detect YOLOv4 CPU FP32 ../../weights/yolov4_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv4 GPU FP32 ../../weights/yolov4_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv4 CPU FP16 ../../weights/yolov4_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv4 GPU FP16 ../../weights/yolov4_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv4 CPU INT8 ../../weights/yolov4_int8.xml bus.jpg
./yolo OpenVINO Detect YOLOv4 GPU INT8 ../../weights/yolov4_int8.xml bus.jpg
./yolo TensorRT Detect YOLOv4 GPU FP32 ../../weights/yolov4_fp32.engine bus.jpg
./yolo TensorRT Detect YOLOv4 GPU FP16 ../../weights/yolov4_fp16.engine bus.jpg
./yolo TensorRT Detect YOLOv4 GPU INT8 ../../weights/yolov4_int8.engine bus.jpg


./yolo Libtorch Classify YOLOv5 CPU FP32 ../../weights/yolov5n_cls_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Classify YOLOv5 GPU FP32 ../../weights/yolov5n_cls_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Classify YOLOv5 GPU FP16 ../../weights/yolov5n_cls_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Classify YOLOv5 CPU FP32 ../../weights/yolov5n_cls_fp32.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv5 GPU FP32 ../../weights/yolov5n_cls_fp32.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv5 CPU FP16 ../../weights/yolov5n_cls_fp16.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv5 GPU FP16 ../../weights/yolov5n_cls_fp16.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv5 CPU INT8 ../../weights/yolov5n_cls_int8.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv5 GPU INT8 ../../weights/yolov5n_cls_int8.onnx bus.jpg
./yolo OpenCV Classify YOLOv5 CPU FP32 ../../weights/yolov5n_cls_fp32.onnx bus.jpg
./yolo OpenCV Classify YOLOv5 GPU FP32 ../../weights/yolov5n_cls_fp32.onnx bus.jpg
./yolo OpenCV Classify YOLOv5 CPU FP16 ../../weights/yolov5n_cls_fp16.onnx bus.jpg
./yolo OpenCV Classify YOLOv5 GPU FP16 ../../weights/yolov5n_cls_fp16.onnx bus.jpg
./yolo OpenVINO Classify YOLOv5 CPU FP32 ../../weights/yolov5n_cls_fp32.xml bus.jpg
./yolo OpenVINO Classify YOLOv5 GPU FP32 ../../weights/yolov5n_cls_fp32.xml bus.jpg
./yolo OpenVINO Classify YOLOv5 CPU FP16 ../../weights/yolov5n_cls_fp16.xml bus.jpg
./yolo OpenVINO Classify YOLOv5 GPU FP16 ../../weights/yolov5n_cls_fp16.xml bus.jpg
./yolo OpenVINO Classify YOLOv5 CPU INT8 ../../weights/yolov5n_cls_int8.xml bus.jpg
./yolo OpenVINO Classify YOLOv5 GPU INT8 ../../weights/yolov5n_cls_int8.xml bus.jpg
./yolo TensorRT Classify YOLOv5 GPU FP32 ../../weights/yolov5n_cls_fp32.engine bus.jpg
./yolo TensorRT Classify YOLOv5 GPU FP16 ../../weights/yolov5n_cls_fp16.engine bus.jpg
./yolo TensorRT Classify YOLOv5 GPU INT8 ../../weights/yolov5n_cls_int8.engine bus.jpg

./yolo Libtorch Detect YOLOv5 CPU FP32 ../../weights/yolov5n_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv5 GPU FP32 ../../weights/yolov5n_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv5 GPU FP16 ../../weights/yolov5n_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Detect YOLOv5 CPU FP32 ../../weights/yolov5n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv5 GPU FP32 ../../weights/yolov5n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv5 CPU FP16 ../../weights/yolov5n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv5 GPU FP16 ../../weights/yolov5n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv5 CPU INT8 ../../weights/yolov5n_int8.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv5 GPU INT8 ../../weights/yolov5n_int8.onnx bus.jpg
./yolo OpenCV Detect YOLOv5 CPU FP32 ../../weights/yolov5n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv5 GPU FP32 ../../weights/yolov5n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv5 CPU FP16 ../../weights/yolov5n_fp16.onnx bus.jpg
./yolo OpenCV Detect YOLOv5 GPU FP16 ../../weights/yolov5n_fp16.onnx bus.jpg
./yolo OpenVINO Detect YOLOv5 CPU FP32 ../../weights/yolov5n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv5 GPU FP32 ../../weights/yolov5n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv5 CPU FP16 ../../weights/yolov5n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv5 GPU FP16 ../../weights/yolov5n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv5 CPU INT8 ../../weights/yolov5n_int8.xml bus.jpg
./yolo OpenVINO Detect YOLOv5 GPU INT8 ../../weights/yolov5n_int8.xml bus.jpg
./yolo TensorRT Detect YOLOv5 GPU FP32 ../../weights/yolov5n_fp32.engine bus.jpg
./yolo TensorRT Detect YOLOv5 GPU FP16 ../../weights/yolov5n_fp16.engine bus.jpg
./yolo TensorRT Detect YOLOv5 GPU INT8 ../../weights/yolov5n_int8.engine bus.jpg

./yolo Libtorch Segment YOLOv5 CPU FP32 ../../weights/yolov5n_seg_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Segment YOLOv5 GPU FP32 ../../weights/yolov5n_seg_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Segment YOLOv5 GPU FP16 ../../weights/yolov5n_seg_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Segment YOLOv5 CPU FP32 ../../weights/yolov5n_seg_fp32.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv5 GPU FP32 ../../weights/yolov5n_seg_fp32.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv5 CPU FP16 ../../weights/yolov5n_seg_fp16.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv5 GPU FP16 ../../weights/yolov5n_seg_fp16.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv5 CPU INT8 ../../weights/yolov5n_seg_int8.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv5 GPU INT8 ../../weights/yolov5n_seg_int8.onnx bus.jpg
./yolo OpenCV Segment YOLOv5 CPU FP32 ../../weights/yolov5n_seg_fp32.onnx bus.jpg
./yolo OpenCV Segment YOLOv5 GPU FP32 ../../weights/yolov5n_seg_fp32.onnx bus.jpg
./yolo OpenCV Segment YOLOv5 CPU FP16 ../../weights/yolov5n_seg_fp16.onnx bus.jpg
./yolo OpenCV Segment YOLOv5 GPU FP16 ../../weights/yolov5n_seg_fp16.onnx bus.jpg
./yolo OpenVINO Segment YOLOv5 CPU FP32 ../../weights/yolov5n_seg_fp32.xml bus.jpg
./yolo OpenVINO Segment YOLOv5 GPU FP32 ../../weights/yolov5n_seg_fp32.xml bus.jpg
./yolo OpenVINO Segment YOLOv5 CPU FP16 ../../weights/yolov5n_seg_fp16.xml bus.jpg
./yolo OpenVINO Segment YOLOv5 GPU FP16 ../../weights/yolov5n_seg_fp16.xml bus.jpg
./yolo OpenVINO Segment YOLOv5 CPU INT8 ../../weights/yolov5n_seg_int8.xml bus.jpg
./yolo OpenVINO Segment YOLOv5 GPU INT8 ../../weights/yolov5n_seg_int8.xml bus.jpg
./yolo TensorRT Segment YOLOv5 GPU FP32 ../../weights/yolov5n_seg_fp32.engine bus.jpg
./yolo TensorRT Segment YOLOv5 GPU FP16 ../../weights/yolov5n_seg_fp16.engine bus.jpg
./yolo TensorRT Segment YOLOv5 GPU INT8 ../../weights/yolov5n_seg_int8.engine bus.jpg


./yolo Libtorch Detect YOLOv6 CPU FP32 ../../weights/yolov6n_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv6 GPU FP32 ../../weights/yolov6n_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv6 GPU FP16 ../../weights/yolov6n_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Detect YOLOv6 CPU FP32 ../../weights/yolov6n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv6 GPU FP32 ../../weights/yolov6n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv6 CPU FP16 ../../weights/yolov6n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv6 GPU FP16 ../../weights/yolov6n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv6 CPU INT8 ../../weights/yolov6n_int8.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv6 GPU INT8 ../../weights/yolov6n_int8.onnx bus.jpg
./yolo OpenCV Detect YOLOv6 CPU FP32 ../../weights/yolov6n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv6 GPU FP32 ../../weights/yolov6n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv6 CPU FP16 ../../weights/yolov6n_fp16.onnx bus.jpg
./yolo OpenCV Detect YOLOv6 GPU FP16 ../../weights/yolov6n_fp16.onnx bus.jpg
./yolo OpenVINO Detect YOLOv6 CPU FP32 ../../weights/yolov6n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv6 GPU FP32 ../../weights/yolov6n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv6 CPU FP16 ../../weights/yolov6n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv6 GPU FP16 ../../weights/yolov6n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv6 CPU INT8 ../../weights/yolov6n_int8.xml bus.jpg
./yolo OpenVINO Detect YOLOv6 GPU INT8 ../../weights/yolov6n_int8.xml bus.jpg
./yolo TensorRT Detect YOLOv6 GPU FP32 ../../weights/yolov6n_fp32.engine bus.jpg
./yolo TensorRT Detect YOLOv6 GPU FP16 ../../weights/yolov6n_fp16.engine bus.jpg
./yolo TensorRT Detect YOLOv6 GPU INT8 ../../weights/yolov6n_int8.engine bus.jpg


./yolo Libtorch Detect YOLOv7 CPU FP32 ../../weights/yolov7t_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv7 GPU FP32 ../../weights/yolov7t_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv7 GPU FP16 ../../weights/yolov7t_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Detect YOLOv7 CPU FP32 ../../weights/yolov7t_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv7 GPU FP32 ../../weights/yolov7t_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv7 CPU FP16 ../../weights/yolov7t_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv7 GPU FP16 ../../weights/yolov7t_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv7 CPU INT8 ../../weights/yolov7t_int8.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv7 GPU INT8 ../../weights/yolov7t_int8.onnx bus.jpg
./yolo OpenCV Detect YOLOv7 CPU FP32 ../../weights/yolov7t_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv7 GPU FP32 ../../weights/yolov7t_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv7 CPU FP16 ../../weights/yolov7t_fp16.onnx bus.jpg
./yolo OpenCV Detect YOLOv7 GPU FP16 ../../weights/yolov7t_fp16.onnx bus.jpg
./yolo OpenVINO Detect YOLOv7 CPU FP32 ../../weights/yolov7t_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv7 GPU FP32 ../../weights/yolov7t_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv7 CPU FP16 ../../weights/yolov7t_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv7 GPU FP16 ../../weights/yolov7t_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv7 CPU INT8 ../../weights/yolov7t_int8.xml bus.jpg
./yolo OpenVINO Detect YOLOv7 GPU INT8 ../../weights/yolov7t_int8.xml bus.jpg
./yolo TensorRT Detect YOLOv7 GPU FP32 ../../weights/yolov7t_fp32.engine bus.jpg
./yolo TensorRT Detect YOLOv7 GPU FP16 ../../weights/yolov7t_fp16.engine bus.jpg
./yolo TensorRT Detect YOLOv7 GPU INT8 ../../weights/yolov7t_int8.engine bus.jpg


./yolo Libtorch Classify YOLOv8 CPU FP32 ../../weights/yolov8n_cls_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Classify YOLOv8 GPU FP32 ../../weights/yolov8n_cls_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Classify YOLOv8 GPU FP16 ../../weights/yolov8n_cls_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Classify YOLOv8 CPU FP32 ../../weights/yolov8n_cls_fp32.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv8 GPU FP32 ../../weights/yolov8n_cls_fp32.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv8 CPU FP16 ../../weights/yolov8n_cls_fp16.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv8 GPU FP16 ../../weights/yolov8n_cls_fp16.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv8 CPU INT8 ../../weights/yolov8n_cls_int8.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv8 GPU INT8 ../../weights/yolov8n_cls_int8.onnx bus.jpg
./yolo OpenCV Classify YOLOv8 CPU FP32 ../../weights/yolov8n_cls_fp32.onnx bus.jpg
./yolo OpenCV Classify YOLOv8 GPU FP32 ../../weights/yolov8n_cls_fp32.onnx bus.jpg
./yolo OpenCV Classify YOLOv8 CPU FP16 ../../weights/yolov8n_cls_fp16.onnx bus.jpg
./yolo OpenCV Classify YOLOv8 GPU FP16 ../../weights/yolov8n_cls_fp16.onnx bus.jpg
./yolo OpenVINO Classify YOLOv8 CPU FP32 ../../weights/yolov8n_cls_fp32.xml bus.jpg
./yolo OpenVINO Classify YOLOv8 GPU FP32 ../../weights/yolov8n_cls_fp32.xml bus.jpg
./yolo OpenVINO Classify YOLOv8 CPU FP16 ../../weights/yolov8n_cls_fp16.xml bus.jpg
./yolo OpenVINO Classify YOLOv8 GPU FP16 ../../weights/yolov8n_cls_fp16.xml bus.jpg
./yolo OpenVINO Classify YOLOv8 CPU INT8 ../../weights/yolov8n_cls_int8.xml bus.jpg
./yolo OpenVINO Classify YOLOv8 GPU INT8 ../../weights/yolov8n_cls_int8.xml bus.jpg
./yolo TensorRT Classify YOLOv8 GPU FP32 ../../weights/yolov8n_cls_fp32.engine bus.jpg
./yolo TensorRT Classify YOLOv8 GPU FP16 ../../weights/yolov8n_cls_fp16.engine bus.jpg
./yolo TensorRT Classify YOLOv8 GPU INT8 ../../weights/yolov8n_cls_int8.engine bus.jpg

./yolo Libtorch Detect YOLOv8 CPU FP32 ../../weights/yolov8n_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv8 GPU FP32 ../../weights/yolov8n_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv8 GPU FP16 ../../weights/yolov8n_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Detect YOLOv8 CPU FP32 ../../weights/yolov8n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv8 GPU FP32 ../../weights/yolov8n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv8 CPU FP16 ../../weights/yolov8n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv8 GPU FP16 ../../weights/yolov8n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv8 CPU INT8 ../../weights/yolov8n_int8.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv8 GPU INT8 ../../weights/yolov8n_int8.onnx bus.jpg
./yolo OpenCV Detect YOLOv8 CPU FP32 ../../weights/yolov8n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv8 GPU FP32 ../../weights/yolov8n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv8 CPU FP16 ../../weights/yolov8n_fp16.onnx bus.jpg
./yolo OpenCV Detect YOLOv8 GPU FP16 ../../weights/yolov8n_fp16.onnx bus.jpg
./yolo OpenVINO Detect YOLOv8 CPU FP32 ../../weights/yolov8n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv8 GPU FP32 ../../weights/yolov8n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv8 CPU FP16 ../../weights/yolov8n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv8 GPU FP16 ../../weights/yolov8n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv8 CPU INT8 ../../weights/yolov8n_int8.xml bus.jpg
./yolo OpenVINO Detect YOLOv8 GPU INT8 ../../weights/yolov8n_int8.xml bus.jpg
./yolo TensorRT Detect YOLOv8 GPU FP32 ../../weights/yolov8n_fp32.engine bus.jpg
./yolo TensorRT Detect YOLOv8 GPU FP16 ../../weights/yolov8n_fp16.engine bus.jpg
./yolo TensorRT Detect YOLOv8 GPU INT8 ../../weights/yolov8n_int8.engine bus.jpg

./yolo Libtorch Segment YOLOv8 CPU FP32 ../../weights/yolov8n_seg_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Segment YOLOv8 GPU FP32 ../../weights/yolov8n_seg_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Segment YOLOv8 GPU FP16 ../../weights/yolov8n_seg_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Segment YOLOv8 CPU FP32 ../../weights/yolov8n_seg_fp32.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv8 GPU FP32 ../../weights/yolov8n_seg_fp32.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv8 CPU FP16 ../../weights/yolov8n_seg_fp16.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv8 GPU FP16 ../../weights/yolov8n_seg_fp16.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv8 CPU INT8 ../../weights/yolov8n_seg_int8.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv8 GPU INT8 ../../weights/yolov8n_seg_int8.onnx bus.jpg
./yolo OpenCV Segment YOLOv8 CPU FP32 ../../weights/yolov8n_seg_fp32.onnx bus.jpg
./yolo OpenCV Segment YOLOv8 GPU FP32 ../../weights/yolov8n_seg_fp32.onnx bus.jpg
./yolo OpenCV Segment YOLOv8 CPU FP16 ../../weights/yolov8n_seg_fp16.onnx bus.jpg
./yolo OpenCV Segment YOLOv8 GPU FP16 ../../weights/yolov8n_seg_fp16.onnx bus.jpg
./yolo OpenVINO Segment YOLOv8 CPU FP32 ../../weights/yolov8n_seg_fp32.xml bus.jpg
./yolo OpenVINO Segment YOLOv8 GPU FP32 ../../weights/yolov8n_seg_fp32.xml bus.jpg
./yolo OpenVINO Segment YOLOv8 CPU FP16 ../../weights/yolov8n_seg_fp16.xml bus.jpg
./yolo OpenVINO Segment YOLOv8 GPU FP16 ../../weights/yolov8n_seg_fp16.xml bus.jpg
./yolo OpenVINO Segment YOLOv8 CPU INT8 ../../weights/yolov8n_seg_int8.xml bus.jpg
./yolo OpenVINO Segment YOLOv8 GPU INT8 ../../weights/yolov8n_seg_int8.xml bus.jpg
./yolo TensorRT Segment YOLOv8 GPU FP32 ../../weights/yolov8n_seg_fp32.engine bus.jpg
./yolo TensorRT Segment YOLOv8 GPU FP16 ../../weights/yolov8n_seg_fp16.engine bus.jpg
./yolo TensorRT Segment YOLOv8 GPU INT8 ../../weights/yolov8n_seg_int8.engine bus.jpg

./yolo Libtorch Pose YOLOv8 CPU FP32 ../../weights/yolov8n_pose_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Pose YOLOv8 GPU FP32 ../../weights/yolov8n_pose_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Pose YOLOv8 GPU FP16 ../../weights/yolov8n_pose_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Pose YOLOv8 CPU FP32 ../../weights/yolov8n_pose_fp32.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv8 GPU FP32 ../../weights/yolov8n_pose_fp32.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv8 CPU FP16 ../../weights/yolov8n_pose_fp16.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv8 GPU FP16 ../../weights/yolov8n_pose_fp16.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv8 CPU INT8 ../../weights/yolov8n_pose_int8.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv8 GPU INT8 ../../weights/yolov8n_pose_int8.onnx bus.jpg
./yolo OpenCV Pose YOLOv8 CPU FP32 ../../weights/yolov8n_pose_fp32.onnx bus.jpg
./yolo OpenCV Pose YOLOv8 GPU FP32 ../../weights/yolov8n_pose_fp32.onnx bus.jpg
./yolo OpenCV Pose YOLOv8 CPU FP16 ../../weights/yolov8n_pose_fp16.onnx bus.jpg
./yolo OpenCV Pose YOLOv8 GPU FP16 ../../weights/yolov8n_pose_fp16.onnx bus.jpg
./yolo OpenVINO Pose YOLOv8 CPU FP32 ../../weights/yolov8n_pose_fp32.xml bus.jpg
./yolo OpenVINO Pose YOLOv8 GPU FP32 ../../weights/yolov8n_pose_fp32.xml bus.jpg
./yolo OpenVINO Pose YOLOv8 CPU FP16 ../../weights/yolov8n_pose_fp16.xml bus.jpg
./yolo OpenVINO Pose YOLOv8 GPU FP16 ../../weights/yolov8n_pose_fp16.xml bus.jpg
./yolo OpenVINO Pose YOLOv8 CPU INT8 ../../weights/yolov8n_pose_int8.xml bus.jpg
./yolo OpenVINO Pose YOLOv8 GPU INT8 ../../weights/yolov8n_pose_int8.xml bus.jpg
./yolo TensorRT Pose YOLOv8 GPU FP32 ../../weights/yolov8n_pose_fp32.engine bus.jpg
./yolo TensorRT Pose YOLOv8 GPU FP16 ../../weights/yolov8n_pose_fp16.engine bus.jpg
./yolo TensorRT Pose YOLOv8 GPU INT8 ../../weights/yolov8n_pose_int8.engine bus.jpg

./yolo Libtorch OBB YOLOv8 CPU FP32 ../../weights/yolov8n_obb_fp32_cpu.torchscript boats.jpg
./yolo Libtorch OBB YOLOv8 GPU FP32 ../../weights/yolov8n_obb_fp32_gpu.torchscript boats.jpg
./yolo Libtorch OBB YOLOv8 GPU FP16 ../../weights/yolov8n_obb_fp16_gpu.torchscript boats.jpg
./yolo ONNXRuntime OBB YOLOv8 CPU FP32 ../../weights/yolov8n_obb_fp32.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv8 GPU FP32 ../../weights/yolov8n_obb_fp32.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv8 CPU FP16 ../../weights/yolov8n_obb_fp16.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv8 GPU FP16 ../../weights/yolov8n_obb_fp16.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv8 CPU INT8 ../../weights/yolov8n_obb_int8.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv8 GPU INT8 ../../weights/yolov8n_obb_int8.onnx boats.jpg
./yolo OpenCV OBB YOLOv8 CPU FP32 ../../weights/yolov8n_obb_fp32.onnx boats.jpg
./yolo OpenCV OBB YOLOv8 GPU FP32 ../../weights/yolov8n_obb_fp32.onnx boats.jpg
./yolo OpenCV OBB YOLOv8 CPU FP16 ../../weights/yolov8n_obb_fp16.onnx boats.jpg
./yolo OpenCV OBB YOLOv8 GPU FP16 ../../weights/yolov8n_obb_fp16.onnx boats.jpg
./yolo OpenVINO OBB YOLOv8 CPU FP32 ../../weights/yolov8n_obb_fp32.xml boats.jpg
./yolo OpenVINO OBB YOLOv8 GPU FP32 ../../weights/yolov8n_obb_fp32.xml boats.jpg
./yolo OpenVINO OBB YOLOv8 CPU FP16 ../../weights/yolov8n_obb_fp16.xml boats.jpg
./yolo OpenVINO OBB YOLOv8 GPU FP16 ../../weights/yolov8n_obb_fp16.xml boats.jpg
./yolo OpenVINO OBB YOLOv8 CPU INT8 ../../weights/yolov8n_obb_int8.xml boats.jpg
./yolo OpenVINO OBB YOLOv8 GPU INT8 ../../weights/yolov8n_obb_int8.xml boats.jpg
./yolo TensorRT OBB YOLOv8 GPU FP32 ../../weights/yolov8n_obb_fp32.engine boats.jpg
./yolo TensorRT OBB YOLOv8 GPU FP16 ../../weights/yolov8n_obb_fp16.engine boats.jpg
./yolo TensorRT OBB YOLOv8 GPU INT8 ../../weights/yolov8n_obb_int8.engine boats.jpg

./yolo Libtorch Detect YOLOv9 CPU FP32 ../../weights/yolov9t_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv9 GPU FP32 ../../weights/yolov9t_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv9 GPU FP16 ../../weights/yolov9t_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Detect YOLOv9 CPU FP32 ../../weights/yolov9t_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv9 GPU FP32 ../../weights/yolov9t_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv9 CPU FP16 ../../weights/yolov9t_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv9 GPU FP16 ../../weights/yolov9t_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv9 CPU INT8 ../../weights/yolov9t_int8.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv9 GPU INT8 ../../weights/yolov9t_int8.onnx bus.jpg
./yolo OpenCV Detect YOLOv9 CPU FP32 ../../weights/yolov9t_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv9 GPU FP32 ../../weights/yolov9t_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv9 CPU FP16 ../../weights/yolov9t_fp16.onnx bus.jpg
./yolo OpenCV Detect YOLOv9 GPU FP16 ../../weights/yolov9t_fp16.onnx bus.jpg
./yolo OpenVINO Detect YOLOv9 CPU FP32 ../../weights/yolov9t_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv9 GPU FP32 ../../weights/yolov9t_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv9 CPU FP16 ../../weights/yolov9t_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv9 GPU FP16 ../../weights/yolov9t_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv9 CPU INT8 ../../weights/yolov9t_int8.xml bus.jpg
./yolo OpenVINO Detect YOLOv9 GPU INT8 ../../weights/yolov9t_int8.xml bus.jpg
./yolo TensorRT Detect YOLOv9 GPU FP32 ../../weights/yolov9t_fp32.engine bus.jpg
./yolo TensorRT Detect YOLOv9 GPU FP16 ../../weights/yolov9t_fp16.engine bus.jpg
./yolo TensorRT Detect YOLOv9 GPU INT8 ../../weights/yolov9t_int8.engine bus.jpg

./yolo Libtorch Segment YOLOv9 CPU FP32 ../../weights/yolov9c_seg_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Segment YOLOv9 GPU FP32 ../../weights/yolov9c_seg_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Segment YOLOv9 GPU FP16 ../../weights/yolov9c_seg_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Segment YOLOv9 CPU FP32 ../../weights/yolov9c_seg_fp32.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv9 GPU FP32 ../../weights/yolov9c_seg_fp32.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv9 CPU FP16 ../../weights/yolov9c_seg_fp16.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv9 GPU FP16 ../../weights/yolov9c_seg_fp16.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv9 CPU INT8 ../../weights/yolov9c_seg_int8.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv9 GPU INT8 ../../weights/yolov9c_seg_int8.onnx bus.jpg
./yolo OpenCV Segment YOLOv9 CPU FP32 ../../weights/yolov9c_seg_fp32.onnx bus.jpg
./yolo OpenCV Segment YOLOv9 GPU FP32 ../../weights/yolov9c_seg_fp32.onnx bus.jpg
./yolo OpenCV Segment YOLOv9 CPU FP16 ../../weights/yolov9c_seg_fp16.onnx bus.jpg
./yolo OpenCV Segment YOLOv9 GPU FP16 ../../weights/yolov9c_seg_fp16.onnx bus.jpg
./yolo OpenVINO Segment YOLOv9 CPU FP32 ../../weights/yolov9c_seg_fp32.xml bus.jpg
./yolo OpenVINO Segment YOLOv9 GPU FP32 ../../weights/yolov9c_seg_fp32.xml bus.jpg
./yolo OpenVINO Segment YOLOv9 CPU FP16 ../../weights/yolov9c_seg_fp16.xml bus.jpg
./yolo OpenVINO Segment YOLOv9 GPU FP16 ../../weights/yolov9c_seg_fp16.xml bus.jpg
./yolo OpenVINO Segment YOLOv9 CPU INT8 ../../weights/yolov9c_seg_int8.xml bus.jpg
./yolo OpenVINO Segment YOLOv9 GPU INT8 ../../weights/yolov9c_seg_int8.xml bus.jpg
./yolo TensorRT Segment YOLOv9 GPU FP32 ../../weights/yolov9c_seg_fp32.engine bus.jpg
./yolo TensorRT Segment YOLOv9 GPU FP16 ../../weights/yolov9c_seg_fp16.engine bus.jpg
./yolo TensorRT Segment YOLOv9 GPU INT8 ../../weights/yolov9c_seg_int8.engine bus.jpg


./yolo Libtorch Detect YOLOv10 CPU FP32 ../../weights/yolov10n_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv10 GPU FP32 ../../weights/yolov10n_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv10 GPU FP16 ../../weights/yolov10n_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Detect YOLOv10 CPU FP32 ../../weights/yolov10n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv10 GPU FP32 ../../weights/yolov10n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv10 CPU FP16 ../../weights/yolov10n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv10 GPU FP16 ../../weights/yolov10n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv10 CPU INT8 ../../weights/yolov10n_int8.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv10 GPU INT8 ../../weights/yolov10n_int8.onnx bus.jpg
./yolo OpenCV Detect YOLOv10 CPU FP32 ../../weights/yolov10n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv10 GPU FP32 ../../weights/yolov10n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv10 CPU FP16 ../../weights/yolov10n_fp16.onnx bus.jpg
./yolo OpenCV Detect YOLOv10 GPU FP16 ../../weights/yolov10n_fp16.onnx bus.jpg
./yolo OpenVINO Detect YOLOv10 CPU FP32 ../../weights/yolov10n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv10 GPU FP32 ../../weights/yolov10n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv10 CPU FP16 ../../weights/yolov10n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv10 GPU FP16 ../../weights/yolov10n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv10 CPU INT8 ../../weights/yolov10n_int8.xml bus.jpg
./yolo OpenVINO Detect YOLOv10 GPU INT8 ../../weights/yolov10n_int8.xml bus.jpg
./yolo TensorRT Detect YOLOv10 GPU FP32 ../../weights/yolov10n_fp32.engine bus.jpg
./yolo TensorRT Detect YOLOv10 GPU FP16 ../../weights/yolov10n_fp16.engine bus.jpg
./yolo TensorRT Detect YOLOv10 GPU INT8 ../../weights/yolov10n_int8.engine bus.jpg


./yolo Libtorch Classify YOLOv11 CPU FP32 ../../weights/yolov11n_cls_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Classify YOLOv11 GPU FP32 ../../weights/yolov11n_cls_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Classify YOLOv11 GPU FP16 ../../weights/yolov11n_cls_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Classify YOLOv11 CPU FP32 ../../weights/yolov11n_cls_fp32.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv11 GPU FP32 ../../weights/yolov11n_cls_fp32.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv11 CPU FP16 ../../weights/yolov11n_cls_fp16.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv11 GPU FP16 ../../weights/yolov11n_cls_fp16.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv11 CPU INT8 ../../weights/yolov11n_cls_int8.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv11 GPU INT8 ../../weights/yolov11n_cls_int8.onnx bus.jpg
./yolo OpenCV Classify YOLOv11 CPU FP32 ../../weights/yolov11n_cls_fp32.onnx bus.jpg
./yolo OpenCV Classify YOLOv11 GPU FP32 ../../weights/yolov11n_cls_fp32.onnx bus.jpg
./yolo OpenCV Classify YOLOv11 CPU FP16 ../../weights/yolov11n_cls_fp16.onnx bus.jpg
./yolo OpenCV Classify YOLOv11 GPU FP16 ../../weights/yolov11n_cls_fp16.onnx bus.jpg
./yolo OpenVINO Classify YOLOv11 CPU FP32 ../../weights/yolov11n_cls_fp32.xml bus.jpg
./yolo OpenVINO Classify YOLOv11 GPU FP32 ../../weights/yolov11n_cls_fp32.xml bus.jpg
./yolo OpenVINO Classify YOLOv11 CPU FP16 ../../weights/yolov11n_cls_fp16.xml bus.jpg
./yolo OpenVINO Classify YOLOv11 GPU FP16 ../../weights/yolov11n_cls_fp16.xml bus.jpg
./yolo OpenVINO Classify YOLOv11 CPU INT8 ../../weights/yolov11n_cls_int8.xml bus.jpg
./yolo OpenVINO Classify YOLOv11 GPU INT8 ../../weights/yolov11n_cls_int8.xml bus.jpg
./yolo TensorRT Classify YOLOv11 GPU FP32 ../../weights/yolov11n_cls_fp32.engine bus.jpg
./yolo TensorRT Classify YOLOv11 GPU FP16 ../../weights/yolov11n_cls_fp16.engine bus.jpg
./yolo TensorRT Classify YOLOv11 GPU INT8 ../../weights/yolov11n_cls_int8.engine bus.jpg

./yolo Libtorch Detect YOLOv11 CPU FP32 ../../weights/yolov11n_fp32_cpu.torchscript bus.jpg    
./yolo Libtorch Detect YOLOv11 GPU FP32 ../../weights/yolov11n_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv11 GPU FP16 ../../weights/yolov11n_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Detect YOLOv11 CPU FP32 ../../weights/yolov11n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv11 GPU FP32 ../../weights/yolov11n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv11 CPU FP16 ../../weights/yolov11n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv11 GPU FP16 ../../weights/yolov11n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv11 CPU INT8 ../../weights/yolov11n_int8.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv11 GPU INT8 ../../weights/yolov11n_int8.onnx bus.jpg
./yolo OpenCV Detect YOLOv11 CPU FP32 ../../weights/yolov11n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv11 GPU FP32 ../../weights/yolov11n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv11 CPU FP16 ../../weights/yolov11n_fp16.onnx bus.jpg
./yolo OpenCV Detect YOLOv11 GPU FP16 ../../weights/yolov11n_fp16.onnx bus.jpg
./yolo OpenVINO Detect YOLOv11 CPU FP32 ../../weights/yolov11n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv11 GPU FP32 ../../weights/yolov11n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv11 CPU FP16 ../../weights/yolov11n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv11 GPU FP16 ../../weights/yolov11n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv11 CPU INT8 ../../weights/yolov11n_int8.xml bus.jpg
./yolo OpenVINO Detect YOLOv11 GPU INT8 ../../weights/yolov11n_int8.xml bus.jpg
./yolo TensorRT Detect YOLOv11 GPU FP32 ../../weights/yolov11n_fp32.engine bus.jpg
./yolo TensorRT Detect YOLOv11 GPU FP16 ../../weights/yolov11n_fp16.engine bus.jpg
./yolo TensorRT Detect YOLOv11 GPU INT8 ../../weights/yolov11n_int8.engine bus.jpg

./yolo Libtorch Segment YOLOv11 CPU FP32 ../../weights/yolov11n_seg_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Segment YOLOv11 GPU FP32 ../../weights/yolov11n_seg_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Segment YOLOv11 GPU FP16 ../../weights/yolov11n_seg_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Segment YOLOv11 CPU FP32 ../../weights/yolov11n_seg_fp32.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv11 GPU FP32 ../../weights/yolov11n_seg_fp32.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv11 CPU FP16 ../../weights/yolov11n_seg_fp16.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv11 GPU FP16 ../../weights/yolov11n_seg_fp16.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv11 CPU INT8 ../../weights/yolov11n_seg_int8.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv11 GPU INT8 ../../weights/yolov11n_seg_int8.onnx bus.jpg
./yolo OpenCV Segment YOLOv11 CPU FP32 ../../weights/yolov11n_seg_fp32.onnx bus.jpg
./yolo OpenCV Segment YOLOv11 GPU FP32 ../../weights/yolov11n_seg_fp32.onnx bus.jpg
./yolo OpenCV Segment YOLOv11 CPU FP16 ../../weights/yolov11n_seg_fp16.onnx bus.jpg
./yolo OpenCV Segment YOLOv11 GPU FP16 ../../weights/yolov11n_seg_fp16.onnx bus.jpg
./yolo OpenVINO Segment YOLOv11 CPU FP32 ../../weights/yolov11n_seg_fp32.xml bus.jpg
./yolo OpenVINO Segment YOLOv11 GPU FP32 ../../weights/yolov11n_seg_fp32.xml bus.jpg
./yolo OpenVINO Segment YOLOv11 CPU FP16 ../../weights/yolov11n_seg_fp16.xml bus.jpg
./yolo OpenVINO Segment YOLOv11 GPU FP16 ../../weights/yolov11n_seg_fp16.xml bus.jpg
./yolo OpenVINO Segment YOLOv11 CPU INT8 ../../weights/yolov11n_seg_int8.xml bus.jpg
./yolo OpenVINO Segment YOLOv11 GPU INT8 ../../weights/yolov11n_seg_int8.xml bus.jpg
./yolo TensorRT Segment YOLOv11 GPU FP32 ../../weights/yolov11n_seg_fp32.engine bus.jpg
./yolo TensorRT Segment YOLOv11 GPU FP16 ../../weights/yolov11n_seg_fp16.engine bus.jpg
./yolo TensorRT Segment YOLOv11 GPU INT8 ../../weights/yolov11n_seg_int8.engine bus.jpg

./yolo Libtorch Pose YOLOv11 CPU FP32 ../../weights/yolov11n_pose_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Pose YOLOv11 GPU FP32 ../../weights/yolov11n_pose_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Pose YOLOv11 GPU FP16 ../../weights/yolov11n_pose_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Pose YOLOv11 CPU FP32 ../../weights/yolov11n_pose_fp32.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv11 GPU FP32 ../../weights/yolov11n_pose_fp32.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv11 CPU FP16 ../../weights/yolov11n_pose_fp16.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv11 GPU FP16 ../../weights/yolov11n_pose_fp16.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv11 CPU INT8 ../../weights/yolov11n_pose_int8.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv11 GPU INT8 ../../weights/yolov11n_pose_int8.onnx bus.jpg
./yolo OpenCV Pose YOLOv11 CPU FP32 ../../weights/yolov11n_pose_fp32.onnx bus.jpg
./yolo OpenCV Pose YOLOv11 GPU FP32 ../../weights/yolov11n_pose_fp32.onnx bus.jpg
./yolo OpenCV Pose YOLOv11 CPU FP16 ../../weights/yolov11n_pose_fp16.onnx bus.jpg
./yolo OpenCV Pose YOLOv11 GPU FP16 ../../weights/yolov11n_pose_fp16.onnx bus.jpg
./yolo OpenVINO Pose YOLOv11 CPU FP32 ../../weights/yolov11n_pose_fp32.xml bus.jpg
./yolo OpenVINO Pose YOLOv11 GPU FP32 ../../weights/yolov11n_pose_fp32.xml bus.jpg
./yolo OpenVINO Pose YOLOv11 CPU FP16 ../../weights/yolov11n_pose_fp16.xml bus.jpg
./yolo OpenVINO Pose YOLOv11 GPU FP16 ../../weights/yolov11n_pose_fp16.xml bus.jpg
./yolo OpenVINO Pose YOLOv11 CPU INT8 ../../weights/yolov11n_pose_int8.xml bus.jpg
./yolo OpenVINO Pose YOLOv11 GPU INT8 ../../weights/yolov11n_pose_int8.xml bus.jpg
./yolo TensorRT Pose YOLOv11 GPU FP32 ../../weights/yolov11n_pose_fp32.engine bus.jpg
./yolo TensorRT Pose YOLOv11 GPU FP16 ../../weights/yolov11n_pose_fp16.engine bus.jpg
./yolo TensorRT Pose YOLOv11 GPU INT8 ../../weights/yolov11n_pose_int8.engine bus.jpg

./yolo Libtorch OBB YOLOv11 CPU FP32 ../../weights/yolov11n_obb_fp32_cpu.torchscript boats.jpg
./yolo Libtorch OBB YOLOv11 GPU FP32 ../../weights/yolov11n_obb_fp32_gpu.torchscript boats.jpg
./yolo Libtorch OBB YOLOv11 GPU FP16 ../../weights/yolov11n_obb_fp16_gpu.torchscript boats.jpg
./yolo ONNXRuntime OBB YOLOv11 CPU FP32 ../../weights/yolov11n_obb_fp32.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv11 GPU FP32 ../../weights/yolov11n_obb_fp32.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv11 CPU FP16 ../../weights/yolov11n_obb_fp16.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv11 GPU FP16 ../../weights/yolov11n_obb_fp16.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv11 CPU INT8 ../../weights/yolov11n_obb_int8.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv11 GPU INT8 ../../weights/yolov11n_obb_int8.onnx boats.jpg
./yolo OpenCV OBB YOLOv11 CPU FP32 ../../weights/yolov11n_obb_fp32.onnx boats.jpg
./yolo OpenCV OBB YOLOv11 GPU FP32 ../../weights/yolov11n_obb_fp32.onnx boats.jpg
./yolo OpenCV OBB YOLOv11 CPU FP16 ../../weights/yolov11n_obb_fp16.onnx boats.jpg
./yolo OpenCV OBB YOLOv11 GPU FP16 ../../weights/yolov11n_obb_fp16.onnx boats.jpg
./yolo OpenVINO OBB YOLOv11 CPU FP32 ../../weights/yolov11n_obb_fp32.xml boats.jpg
./yolo OpenVINO OBB YOLOv11 GPU FP32 ../../weights/yolov11n_obb_fp32.xml boats.jpg
./yolo OpenVINO OBB YOLOv11 CPU FP16 ../../weights/yolov11n_obb_fp16.xml boats.jpg
./yolo OpenVINO OBB YOLOv11 GPU FP16 ../../weights/yolov11n_obb_fp16.xml boats.jpg
./yolo OpenVINO OBB YOLOv11 CPU INT8 ../../weights/yolov11n_obb_int8.xml boats.jpg
./yolo OpenVINO OBB YOLOv11 GPU INT8 ../../weights/yolov11n_obb_int8.xml boats.jpg
./yolo TensorRT OBB YOLOv11 GPU FP32 ../../weights/yolov11n_obb_fp32.engine boats.jpg
./yolo TensorRT OBB YOLOv11 GPU FP16 ../../weights/yolov11n_obb_fp16.engine boats.jpg
./yolo TensorRT OBB YOLOv11 GPU INT8 ../../weights/yolov11n_obb_int8.engine boats.jpg


./yolo Libtorch Classify YOLOv12 CPU FP32 ../../weights/yolov12n_cls_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Classify YOLOv12 GPU FP32 ../../weights/yolov12n_cls_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Classify YOLOv12 GPU FP16 ../../weights/yolov12n_cls_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Classify YOLOv12 CPU FP32 ../../weights/yolov12n_cls_fp32.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv12 GPU FP32 ../../weights/yolov12n_cls_fp32.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv12 CPU FP16 ../../weights/yolov12n_cls_fp16.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv12 GPU FP16 ../../weights/yolov12n_cls_fp16.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv12 CPU INT8 ../../weights/yolov12n_cls_int8.onnx bus.jpg
./yolo ONNXRuntime Classify YOLOv12 GPU INT8 ../../weights/yolov12n_cls_int8.onnx bus.jpg
./yolo OpenCV Classify YOLOv12 CPU FP32 ../../weights/yolov12n_cls_fp32.onnx bus.jpg
./yolo OpenCV Classify YOLOv12 GPU FP32 ../../weights/yolov12n_cls_fp32.onnx bus.jpg
./yolo OpenCV Classify YOLOv12 CPU FP16 ../../weights/yolov12n_cls_fp16.onnx bus.jpg
./yolo OpenCV Classify YOLOv12 GPU FP16 ../../weights/yolov12n_cls_fp16.onnx bus.jpg
./yolo OpenVINO Classify YOLOv12 CPU FP32 ../../weights/yolov12n_cls_fp32.xml bus.jpg
./yolo OpenVINO Classify YOLOv12 GPU FP32 ../../weights/yolov12n_cls_fp32.xml bus.jpg
./yolo OpenVINO Classify YOLOv12 CPU FP16 ../../weights/yolov12n_cls_fp16.xml bus.jpg
./yolo OpenVINO Classify YOLOv12 GPU FP16 ../../weights/yolov12n_cls_fp16.xml bus.jpg
./yolo OpenVINO Classify YOLOv12 CPU INT8 ../../weights/yolov12n_cls_int8.xml bus.jpg
./yolo OpenVINO Classify YOLOv12 GPU INT8 ../../weights/yolov12n_cls_int8.xml bus.jpg
./yolo TensorRT Classify YOLOv12 GPU FP32 ../../weights/yolov12n_cls_fp32.engine bus.jpg
./yolo TensorRT Classify YOLOv12 GPU FP16 ../../weights/yolov12n_cls_fp16.engine bus.jpg
./yolo TensorRT Classify YOLOv12 GPU INT8 ../../weights/yolov12n_cls_int8.engine bus.jpg

./yolo Libtorch Detect YOLOv12 CPU FP32 ../../weights/yolov12n_fp32_cpu.torchscript bus.jpg    
./yolo Libtorch Detect YOLOv12 GPU FP32 ../../weights/yolov12n_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv12 GPU FP16 ../../weights/yolov12n_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Detect YOLOv12 CPU FP32 ../../weights/yolov12n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv12 GPU FP32 ../../weights/yolov12n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv12 CPU FP16 ../../weights/yolov12n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv12 GPU FP16 ../../weights/yolov12n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv12 CPU INT8 ../../weights/yolov12n_int8.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv12 GPU INT8 ../../weights/yolov12n_int8.onnx bus.jpg
./yolo OpenCV Detect YOLOv12 CPU FP32 ../../weights/yolov12n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv12 GPU FP32 ../../weights/yolov12n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv12 CPU FP16 ../../weights/yolov12n_fp16.onnx bus.jpg
./yolo OpenCV Detect YOLOv12 GPU FP16 ../../weights/yolov12n_fp16.onnx bus.jpg
./yolo OpenVINO Detect YOLOv12 CPU FP32 ../../weights/yolov12n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv12 GPU FP32 ../../weights/yolov12n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv12 CPU FP16 ../../weights/yolov12n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv12 GPU FP16 ../../weights/yolov12n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv12 CPU INT8 ../../weights/yolov12n_int8.xml bus.jpg
./yolo OpenVINO Detect YOLOv12 GPU INT8 ../../weights/yolov12n_int8.xml bus.jpg
./yolo TensorRT Detect YOLOv12 GPU FP32 ../../weights/yolov12n_fp32.engine bus.jpg
./yolo TensorRT Detect YOLOv12 GPU FP16 ../../weights/yolov12n_fp16.engine bus.jpg
./yolo TensorRT Detect YOLOv12 GPU INT8 ../../weights/yolov12n_int8.engine bus.jpg

./yolo Libtorch Segment YOLOv12 CPU FP32 ../../weights/yolov12n_seg_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Segment YOLOv12 GPU FP32 ../../weights/yolov12n_seg_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Segment YOLOv12 GPU FP16 ../../weights/yolov12n_seg_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Segment YOLOv12 CPU FP32 ../../weights/yolov12n_seg_fp32.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv12 GPU FP32 ../../weights/yolov12n_seg_fp32.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv12 CPU FP16 ../../weights/yolov12n_seg_fp16.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv12 GPU FP16 ../../weights/yolov12n_seg_fp16.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv12 CPU INT8 ../../weights/yolov12n_seg_int8.onnx bus.jpg
./yolo ONNXRuntime Segment YOLOv12 GPU INT8 ../../weights/yolov12n_seg_int8.onnx bus.jpg
./yolo OpenCV Segment YOLOv12 CPU FP32 ../../weights/yolov12n_seg_fp32.onnx bus.jpg
./yolo OpenCV Segment YOLOv12 GPU FP32 ../../weights/yolov12n_seg_fp32.onnx bus.jpg
./yolo OpenCV Segment YOLOv12 CPU FP16 ../../weights/yolov12n_seg_fp16.onnx bus.jpg
./yolo OpenCV Segment YOLOv12 GPU FP16 ../../weights/yolov12n_seg_fp16.onnx bus.jpg
./yolo OpenVINO Segment YOLOv12 CPU FP32 ../../weights/yolov12n_seg_fp32.xml bus.jpg
./yolo OpenVINO Segment YOLOv12 GPU FP32 ../../weights/yolov12n_seg_fp32.xml bus.jpg
./yolo OpenVINO Segment YOLOv12 CPU FP16 ../../weights/yolov12n_seg_fp16.xml bus.jpg
./yolo OpenVINO Segment YOLOv12 GPU FP16 ../../weights/yolov12n_seg_fp16.xml bus.jpg
./yolo OpenVINO Segment YOLOv12 CPU INT8 ../../weights/yolov12n_seg_int8.xml bus.jpg
./yolo OpenVINO Segment YOLOv12 GPU INT8 ../../weights/yolov12n_seg_int8.xml bus.jpg
./yolo TensorRT Segment YOLOv12 GPU FP32 ../../weights/yolov12n_seg_fp32.engine bus.jpg
./yolo TensorRT Segment YOLOv12 GPU FP16 ../../weights/yolov12n_seg_fp16.engine bus.jpg
./yolo TensorRT Segment YOLOv12 GPU INT8 ../../weights/yolov12n_seg_int8.engine bus.jpg

./yolo Libtorch Pose YOLOv12 CPU FP32 ../../weights/yolov12n_pose_fp32_cpu.torchscript bus.jpg
./yolo Libtorch Pose YOLOv12 GPU FP32 ../../weights/yolov12n_pose_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Pose YOLOv12 GPU FP16 ../../weights/yolov12n_pose_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Pose YOLOv12 CPU FP32 ../../weights/yolov12n_pose_fp32.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv12 GPU FP32 ../../weights/yolov12n_pose_fp32.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv12 CPU FP16 ../../weights/yolov12n_pose_fp16.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv12 GPU FP16 ../../weights/yolov12n_pose_fp16.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv12 CPU INT8 ../../weights/yolov12n_pose_int8.onnx bus.jpg
./yolo ONNXRuntime Pose YOLOv12 GPU INT8 ../../weights/yolov12n_pose_int8.onnx bus.jpg
./yolo OpenCV Pose YOLOv12 CPU FP32 ../../weights/yolov12n_pose_fp32.onnx bus.jpg
./yolo OpenCV Pose YOLOv12 GPU FP32 ../../weights/yolov12n_pose_fp32.onnx bus.jpg
./yolo OpenCV Pose YOLOv12 CPU FP16 ../../weights/yolov12n_pose_fp16.onnx bus.jpg
./yolo OpenCV Pose YOLOv12 GPU FP16 ../../weights/yolov12n_pose_fp16.onnx bus.jpg
./yolo OpenVINO Pose YOLOv12 CPU FP32 ../../weights/yolov12n_pose_fp32.xml bus.jpg
./yolo OpenVINO Pose YOLOv12 GPU FP32 ../../weights/yolov12n_pose_fp32.xml bus.jpg
./yolo OpenVINO Pose YOLOv12 CPU FP16 ../../weights/yolov12n_pose_fp16.xml bus.jpg
./yolo OpenVINO Pose YOLOv12 GPU FP16 ../../weights/yolov12n_pose_fp16.xml bus.jpg
./yolo OpenVINO Pose YOLOv12 CPU INT8 ../../weights/yolov12n_pose_int8.xml bus.jpg
./yolo OpenVINO Pose YOLOv12 GPU INT8 ../../weights/yolov12n_pose_int8.xml bus.jpg
./yolo TensorRT Pose YOLOv12 GPU FP32 ../../weights/yolov12n_pose_fp32.engine bus.jpg
./yolo TensorRT Pose YOLOv12 GPU FP16 ../../weights/yolov12n_pose_fp16.engine bus.jpg
./yolo TensorRT Pose YOLOv12 GPU INT8 ../../weights/yolov12n_pose_int8.engine bus.jpg

./yolo Libtorch OBB YOLOv12 CPU FP32 ../../weights/yolov12n_obb_fp32_cpu.torchscript boats.jpg
./yolo Libtorch OBB YOLOv12 GPU FP32 ../../weights/yolov12n_obb_fp32_gpu.torchscript boats.jpg
./yolo Libtorch OBB YOLOv12 GPU FP16 ../../weights/yolov12n_obb_fp16_gpu.torchscript boats.jpg
./yolo ONNXRuntime OBB YOLOv12 CPU FP32 ../../weights/yolov12n_obb_fp32.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv12 GPU FP32 ../../weights/yolov12n_obb_fp32.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv12 CPU FP16 ../../weights/yolov12n_obb_fp16.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv12 GPU FP16 ../../weights/yolov12n_obb_fp16.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv12 CPU INT8 ../../weights/yolov12n_obb_int8.onnx boats.jpg
./yolo ONNXRuntime OBB YOLOv12 GPU INT8 ../../weights/yolov12n_obb_int8.onnx boats.jpg
./yolo OpenCV OBB YOLOv12 CPU FP32 ../../weights/yolov12n_obb_fp32.onnx boats.jpg
./yolo OpenCV OBB YOLOv12 GPU FP32 ../../weights/yolov12n_obb_fp32.onnx boats.jpg
./yolo OpenCV OBB YOLOv12 CPU FP16 ../../weights/yolov12n_obb_fp16.onnx boats.jpg
./yolo OpenCV OBB YOLOv12 GPU FP16 ../../weights/yolov12n_obb_fp16.onnx boats.jpg
./yolo OpenVINO OBB YOLOv12 CPU FP32 ../../weights/yolov12n_obb_fp32.xml boats.jpg
./yolo OpenVINO OBB YOLOv12 GPU FP32 ../../weights/yolov12n_obb_fp32.xml boats.jpg
./yolo OpenVINO OBB YOLOv12 CPU FP16 ../../weights/yolov12n_obb_fp16.xml boats.jpg
./yolo OpenVINO OBB YOLOv12 GPU FP16 ../../weights/yolov12n_obb_fp16.xml boats.jpg
./yolo OpenVINO OBB YOLOv12 CPU INT8 ../../weights/yolov12n_obb_int8.xml boats.jpg
./yolo OpenVINO OBB YOLOv12 GPU INT8 ../../weights/yolov12n_obb_int8.xml boats.jpg
./yolo TensorRT OBB YOLOv12 GPU FP32 ../../weights/yolov12n_obb_fp32.engine boats.jpg
./yolo TensorRT OBB YOLOv12 GPU FP16 ../../weights/yolov12n_obb_fp16.engine boats.jpg
./yolo TensorRT OBB YOLOv12 GPU INT8 ../../weights/yolov12n_obb_int8.engine boats.jpg


./yolo Libtorch Detect YOLOv13 CPU FP32 ../../weights/yolov13n_fp32_cpu.torchscript bus.jpg    
./yolo Libtorch Detect YOLOv13 GPU FP32 ../../weights/yolov13n_fp32_gpu.torchscript bus.jpg
./yolo Libtorch Detect YOLOv13 GPU FP16 ../../weights/yolov13n_fp16_gpu.torchscript bus.jpg
./yolo ONNXRuntime Detect YOLOv13 CPU FP32 ../../weights/yolov13n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv13 GPU FP32 ../../weights/yolov13n_fp32.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv13 CPU FP16 ../../weights/yolov13n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv13 GPU FP16 ../../weights/yolov13n_fp16.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv13 CPU INT8 ../../weights/yolov13n_int8.onnx bus.jpg
./yolo ONNXRuntime Detect YOLOv13 GPU INT8 ../../weights/yolov13n_int8.onnx bus.jpg
./yolo OpenCV Detect YOLOv13 CPU FP32 ../../weights/yolov13n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv13 GPU FP32 ../../weights/yolov13n_fp32.onnx bus.jpg
./yolo OpenCV Detect YOLOv13 CPU FP16 ../../weights/yolov13n_fp16.onnx bus.jpg
./yolo OpenCV Detect YOLOv13 GPU FP16 ../../weights/yolov13n_fp16.onnx bus.jpg
./yolo OpenVINO Detect YOLOv13 CPU FP32 ../../weights/yolov13n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv13 GPU FP32 ../../weights/yolov13n_fp32.xml bus.jpg
./yolo OpenVINO Detect YOLOv13 CPU FP16 ../../weights/yolov13n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv13 GPU FP16 ../../weights/yolov13n_fp16.xml bus.jpg
./yolo OpenVINO Detect YOLOv13 CPU INT8 ../../weights/yolov13n_int8.xml bus.jpg
./yolo OpenVINO Detect YOLOv13 GPU INT8 ../../weights/yolov13n_int8.xml bus.jpg
./yolo TensorRT Detect YOLOv13 GPU FP32 ../../weights/yolov13n_fp32.engine bus.jpg
./yolo TensorRT Detect YOLOv13 GPU FP16 ../../weights/yolov13n_fp16.engine bus.jpg
./yolo TensorRT Detect YOLOv13 GPU INT8 ../../weights/yolov13n_int8.engine bus.jpg
