python main.py --algo_type YOLOv3 --backend_type PyTorch --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov3u_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov3u_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov3u_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov3u_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov3u_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov3u_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv3 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov3u_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov3u_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov3u_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov3u_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov3u_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov3u_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov3u_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov3u_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov3u_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov3u_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov3u_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv3  --backend_type OpenVINO --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov3u_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov3u_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov3u_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov3u_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv3 --backend_type TensorRT --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov3u_int8.engine --input_path bus.jpg


python main.py --algo_type YOLOv4 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov4_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov4_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov4_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv4 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov4_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov4_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov4_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov4_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov4_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov4_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov4_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov4_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov4_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov4_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov4_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov4_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov4_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov4_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov4_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv4 --backend_type TensorRT --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov4_int8.engine --input_path bus.jpg


python main.py --algo_type YOLOv5 --backend_type PyTorch --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_cls_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type PyTorch --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_cls_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type PyTorch --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_cls_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov5n_cls_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type INT8 --model_path ../weights/yolov5n_cls_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov5n_cls_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov5n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_cls_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_cls_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov5n_cls_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_cls_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type INT8 --model_path ../weights/yolov5n_cls_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov5n_cls_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type TensorRT --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_cls_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type TensorRT --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_cls_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type TensorRT --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov5n_cls_int8.engine --input_path bus.jpg

python main.py --algo_type YOLOv5 --backend_type PyTorch --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov5n_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov5n_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov5n_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov5n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov5n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov5n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov5n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type TensorRT --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov5n_int8.engine --input_path bus.jpg

python main.py --algo_type YOLOv5 --backend_type PyTorch --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_seg_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type PyTorch --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_seg_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type PyTorch --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_seg_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov5n_seg_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type INT8 --model_path ../weights/yolov5n_seg_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov5n_seg_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov5n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenCV --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov5n_seg_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_seg_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov5n_seg_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_seg_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type INT8 --model_path ../weights/yolov5n_seg_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov5n_seg_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type TensorRT --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov5n_seg_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type TensorRT --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov5n_seg_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv5 --backend_type TensorRT --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov5n_seg_int8.engine --input_path bus.jpg


python main.py --algo_type YOLOv6 --backend_type PyTorch --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov6n_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov6n_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov6n_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov6n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov6n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov6n_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv6 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov6n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov6n_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov6n_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov6n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov6n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov6n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov6n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov6n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov6n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov6n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov6n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov6n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov6n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov6n_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov6n_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv6 --backend_type TensorRT --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov6n_int8.engine --input_path bus.jpg


python main.py --algo_type YOLOv7 --backend_type PyTorch --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov7t_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov7t_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov7t_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov7t_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov7t_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov7t_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv7 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov7t_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov7t_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov7t_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov7t_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov7t_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov7t_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov7t_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov7t_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov7t_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov7t_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov7t_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov7t_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov7t_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov7t_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov7t_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv7 --backend_type TensorRT --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov7t_int8.engine --input_path bus.jpg


python main.py --algo_type YOLOv8 --backend_type PyTorch --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_cls_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type PyTorch --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_cls_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type PyTorch --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_cls_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov8n_cls_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type INT8 --model_path ../weights/yolov8n_cls_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov8n_cls_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov8n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_cls_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_cls_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov8n_cls_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_cls_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type INT8 --model_path ../weights/yolov8n_cls_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov8n_cls_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type TensorRT --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_cls_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type TensorRT --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_cls_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type TensorRT --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov8n_cls_int8.engine --input_path bus.jpg

python main.py --algo_type YOLOv8 --backend_type PyTorch --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov8n_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov8n_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov8n_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov8n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov8n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov8n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov8n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type TensorRT --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov8n_int8.engine --input_path bus.jpg

python main.py --algo_type YOLOv8 --backend_type PyTorch --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_seg_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type PyTorch --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_seg_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type PyTorch --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_seg_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov8n_seg_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type INT8 --model_path ../weights/yolov8n_seg_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov8n_seg_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov8n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenCV --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov8n_seg_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_seg_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov8n_seg_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_seg_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type INT8 --model_path ../weights/yolov8n_seg_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov8n_seg_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type TensorRT --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov8n_seg_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type TensorRT --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov8n_seg_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv8 --backend_type TensorRT --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov8n_seg_int8.engine --input_path bus.jpg


python main.py --algo_type YOLOv9 --backend_type PyTorch --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov9t_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov9t_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov9t_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov9t_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov9t_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov9t_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov9t_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov9t_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov9t_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov9t_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov9t_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov9t_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov9t_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov9t_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov9t_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov9t_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov9t_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov9t_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov9t_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov9t_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov9t_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type TensorRT --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov9t_int8.engine --input_path bus.jpg

python main.py --algo_type YOLOv9 --backend_type PyTorch --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov9c_seg_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type PyTorch --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov9c_seg_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type PyTorch --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov9c_seg_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov9c_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov9c_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov9c_seg_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov9c_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type INT8 --model_path ../weights/yolov9c_seg_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov9c_seg_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenCV --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov9c_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenCV --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov9c_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenCV --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov9c_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenCV --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov9c_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov9c_seg_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov9c_seg_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov9c_seg_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov9c_seg_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type INT8 --model_path ../weights/yolov9c_seg_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov9c_seg_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type TensorRT --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov9c_seg_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type TensorRT --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov9c_seg_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv9 --backend_type TensorRT --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov9c_seg_int8.engine --input_path bus.jpg


python main.py --algo_type YOLOv10 --backend_type PyTorch --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov10n_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov10n_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov10n_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov10n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov10n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov10n_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv10 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov10n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov10n_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov10n_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov10n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov10n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov10n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov10n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov10n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov10n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov10n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov10n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov10n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov10n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov10n_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov10n_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv10 --backend_type TensorRT --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov10n_int8.engine --input_path bus.jpg


python main.py --algo_type YOLOv11 --backend_type PyTorch --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_cls_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type PyTorch --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_cls_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type PyTorch --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_cls_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov11n_cls_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type INT8 --model_path ../weights/yolov11n_cls_int8.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov11n_cls_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov11n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_cls_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_cls_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov11n_cls_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_cls_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type INT8 --model_path ../weights/yolov11n_cls_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov11n_cls_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type TensorRT --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_cls_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type TensorRT --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_cls_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type TensorRT --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov11n_cls_int8.engine --input_path bus.jpg

python main.py --algo_type YOLOv11 --backend_type PyTorch --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov11n_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov11n_int8.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov11n_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov11n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov11n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov11n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov11n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type TensorRT --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov11n_int8.engine --input_path bus.jpg

python main.py --algo_type YOLOv11 --backend_type PyTorch --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_seg_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type PyTorch --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_seg_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type PyTorch --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_seg_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov11n_seg_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type INT8 --model_path ../weights/yolov11n_seg_int8.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv11 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov11n_seg_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov11n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenCV --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov11n_seg_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_seg_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov11n_seg_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_seg_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type INT8 --model_path ../weights/yolov11n_seg_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov11n_seg_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type TensorRT --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov11n_seg_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type TensorRT --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov11n_seg_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv11 --backend_type TensorRT --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov11n_seg_int8.engine --input_path bus.jpg


python main.py --algo_type YOLOv12 --backend_type PyTorch --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_cls_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type PyTorch --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_cls_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type PyTorch --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_cls_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov12n_cls_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Classify --device_type CPU --model_type INT8 --model_path ../weights/yolov12n_cls_int8.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov12n_cls_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_cls_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov12n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_cls_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_cls_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_cls_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type FP16 --model_path ../weights/yolov12n_cls_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_cls_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Classify --device_type CPU --model_type INT8 --model_path ../weights/yolov12n_cls_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov12n_cls_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type TensorRT --task_type Classify --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_cls_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type TensorRT --task_type Classify --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_cls_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type TensorRT --task_type Classify --device_type GPU --model_type INT8 --model_path ../weights/yolov12n_cls_int8.engine --input_path bus.jpg

python main.py --algo_type YOLOv12 --backend_type PyTorch --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov12n_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov12n_int8.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov12n_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov12n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov12n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov12n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov12n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type TensorRT --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov12n_int8.engine --input_path bus.jpg

python main.py --algo_type YOLOv12 --backend_type PyTorch --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_seg_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type PyTorch --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_seg_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type PyTorch --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_seg_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov12n_seg_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Segment --device_type CPU --model_type INT8 --model_path ../weights/yolov12n_seg_int8.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv12 --backend_type ONNXRuntime --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov12n_seg_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_seg_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov12n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenCV --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_seg_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type FP32 --model_path ../weights/yolov12n_seg_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_seg_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type FP16 --model_path ../weights/yolov12n_seg_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_seg_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Segment --device_type CPU --model_type INT8 --model_path ../weights/yolov12n_seg_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type OpenVINO --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov12n_seg_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type TensorRT --task_type Segment --device_type GPU --model_type FP32 --model_path ../weights/yolov12n_seg_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type TensorRT --task_type Segment --device_type GPU --model_type FP16 --model_path ../weights/yolov12n_seg_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv12 --backend_type TensorRT --task_type Segment --device_type GPU --model_type INT8 --model_path ../weights/yolov12n_seg_int8.engine --input_path bus.jpg


python main.py --algo_type YOLOv13 --backend_type PyTorch --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov13n_fp32_cpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov13n_fp32_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type PyTorch --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov13n_fp16_gpu.torchscript --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov13n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov13n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov13n_fp16.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv13 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov13n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type ONNXRuntime --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov13n_int8.onnx --input_path bus.jpg 
python main.py --algo_type YOLOv13 --backend_type ONNXRuntime --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov13n_int8.onnx --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov13n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov13n_fp32.onnx --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type OpenCV --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov13n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type OpenCV --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov13n_fp16.onnx --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP32 --model_path ../weights/yolov13n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov13n_fp32.xml --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type FP16 --model_path ../weights/yolov13n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov13n_fp16.xml --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type OpenVINO --task_type Detect --device_type CPU --model_type INT8 --model_path ../weights/yolov13n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type OpenVINO --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov13n_int8.xml --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP32 --model_path ../weights/yolov13n_fp32.engine --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type TensorRT --task_type Detect --device_type GPU --model_type FP16 --model_path ../weights/yolov13n_fp16.engine --input_path bus.jpg
python main.py --algo_type YOLOv13 --backend_type TensorRT --task_type Detect --device_type GPU --model_type INT8 --model_path ../weights/yolov13n_int8.engine --input_path bus.jpg